// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/publikasi/artikel/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Artikel"
                ],
                "parameters": [
                    {
                        "description": "string",
                        "name": "parameter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ArtikelView"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/publikasi/artikel/delete/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Artikel"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/publikasi/artikel/get-all": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Artikel"
                ],
                "parameters": [
                    {
                        "description": "string",
                        "name": "parameter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Request_Pagination"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/publikasi/artikel/get-one/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Artikel"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/publikasi/artikel/update/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Artikel"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "string",
                        "name": "parameter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ArtikelView"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/publikasi/infografis/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infografis"
                ],
                "parameters": [
                    {
                        "description": "string",
                        "name": "parameter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.InfografisView"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/publikasi/infografis/delete/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infografis"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/publikasi/infografis/get-all": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infografis"
                ],
                "parameters": [
                    {
                        "description": "string",
                        "name": "parameter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Request_Pagination"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/publikasi/infografis/get-one/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infografis"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/publikasi/infografis/update/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infografis"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "string",
                        "name": "parameter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.InfografisView"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "model.ArtikelView": {
            "type": "object",
            "properties": {
                "abstrak": {
                    "type": "string",
                    "example": ""
                },
                "bidang_subjek": {
                    "type": "string",
                    "example": ""
                },
                "judul_jurnal": {
                    "type": "string",
                    "example": ""
                },
                "penerbit_jurnal": {
                    "type": "string",
                    "example": ""
                },
                "penulis_jurnal": {
                    "type": "string",
                    "example": ""
                },
                "tentang_penulis_jurnal": {
                    "type": "string",
                    "example": ""
                }
            }
        },
        "model.InfografisView": {
            "type": "object",
            "properties": {
                "deskripsi": {
                    "type": "string",
                    "example": ""
                },
                "image_slider": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "deskripsi": {
                                "type": "string",
                                "example": ""
                            },
                            "file": {
                                "type": "string",
                                "example": ""
                            }
                        }
                    }
                },
                "judul": {
                    "type": "string",
                    "example": ""
                },
                "kategori": {
                    "type": "string",
                    "example": ""
                },
                "publisher": {
                    "type": "string",
                    "example": ""
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        ""
                    ]
                }
            }
        },
        "model.Request_Pagination": {
            "type": "object",
            "properties": {
                "order": {
                    "type": "string",
                    "example": "ASC"
                },
                "orderBy": {
                    "type": "string",
                    "example": ""
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "type": "integer",
                    "example": 11
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Service Portal-Data-Kalsel",
	Description:      "Portal-Data-Kalsel",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
